# Use the official PostgreSQL image as the base image
FROM postgres:alpine

# Define environment variables
ENV POSTGRES_DB ecommerce
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD secret

# Expose port 5432 to the outside world
EXPOSE 5432
