version: '3'
services:
  web:
    build: ./webserver
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
