# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy your website's files to the Nginx default directory
COPY . /usr/share/nginx/html

# Expose port 80 to allow traffic to reach the web server
EXPOSE 80
